default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

development:
  secret_key_base: your_secret_key_base_value_here


test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
